services:
  quickbooks-online-mcp-server:
    image: questregistry.azurecr.io/quickbooks-online-mcp-server:${SHA}
    container_name: quickbooks-online-mcp
    restart: always
    ports:
      - 8011:3000
    environment:
      - PORT=3000
      - MCP_TRANSPORT=http
    env_file:
      - .env